// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC4KbFYTTDtwPrNheiJnMuakfJ1FQphUI',
    appId: '1:329605235414:web:216b4dc9ec0641bcb97f77',
    messagingSenderId: '329605235414',
    projectId: 'cancel-meals-checker',
    authDomain: 'cancel-meals-checker.firebaseapp.com',
    storageBucket: 'cancel-meals-checker.appspot.com',
    measurementId: 'G-7G82WWZYDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi25ma29aAZHoohrSC6MuGbQWA5tv9nTk',
    appId: '1:329605235414:android:5628fad4381362c4b97f77',
    messagingSenderId: '329605235414',
    projectId: 'cancel-meals-checker',
    storageBucket: 'cancel-meals-checker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNAqoJ5_KcteXo0zlUI0ZfbEw8eWnK2to',
    appId: '1:329605235414:ios:ce7050b589b13479b97f77',
    messagingSenderId: '329605235414',
    projectId: 'cancel-meals-checker',
    storageBucket: 'cancel-meals-checker.appspot.com',
    iosClientId: '329605235414-tgtr5bms5q24pifggs5o18vsr4ie3dcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cancelMealsCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNAqoJ5_KcteXo0zlUI0ZfbEw8eWnK2to',
    appId: '1:329605235414:ios:ce7050b589b13479b97f77',
    messagingSenderId: '329605235414',
    projectId: 'cancel-meals-checker',
    storageBucket: 'cancel-meals-checker.appspot.com',
    iosClientId: '329605235414-tgtr5bms5q24pifggs5o18vsr4ie3dcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cancelMealsCheck',
  );
}
